update: update script usage

diff --git a/scripts/Alert b/scripts/Alert
--- a/scripts/Alert
+++ b/scripts/Alert
@@ -10,6 +10,10 @@ while getopts ':wx' OPTION; do
 		x)
 			failonly=1
 		;;
+		?)
+			echo "script usage: $(basename $0) [-w (Widnow)] [-x (Failonly)]"
+			exit 1
+		;;
 	esac
 done
 shift "$(($OPTIND -1))"
